### ISSUE TITLE
add descriptions to github repos without descriptions

### ISSUE THREAD

**Issue by aimeerivers** [hedia-team/.github#57]
thanks to @rvedotrc for finding them for us!

https://github.com/hedia-team/hedia-server
https://github.com/hedia-team/cli
https://github.com/hedia-team/event-store
https://github.com/hedia-team/pubsub
https://github.com/hedia-team/webhook-service
https://github.com/hedia-team/event-service
https://github.com/hedia-team/iam-service
https://github.com/hedia-team/log-service
https://github.com/hedia-team/id-service
https://github.com/hedia-team/export-service
https://github.com/hedia-team/robots
https://github.com/hedia-team/test-service
https://github.com/hedia-team/test
https://github.com/hedia-team/brand
https://github.com/hedia-team/unit-of-work
https://github.com/hedia-team/streamdeck
https://github.com/hedia-team/.github
https://github.com/hedia-team/favicon
https://github.com/hedia-team/texts
https://github.com/hedia-team/uptimerobot-service
https://github.com/hedia-team/mail
https://github.com/hedia-team/backend-pair-programming
https://github.com/hedia-team/translate
https://github.com/hedia-team/fetch
https://github.com/hedia-team/iconly

**Comment by rvedotrc** [comment]
Handy related command:

```
gh repo view --json=description | jq .description ; jq .description < package.json ; ruby -rjson -e 'puts JSON.generate($stdin.read.sub(/\A#.*/, "").sub(/x/, "").sub(/^#.*/ms, "").strip)' < README.md | jq .
```

**Comment by rvedotrc** [comment]
Done!

```
ls-repos backend | while read repo ; do D=$( jq -r .description < $repo/package.json ) && [ -n "$D" -a "$D" != "null" ] && gh repo edit --description "$D" hedia-team/$repo ; done
```

although only if I had an up-to-date `HEAD` of each repo. Hmmmm.

We could workflow this but it's probably overkill.
